Profbeats/messager/urls.py
from django.urls import path
from . import views

app_name = 'messager'

urlpatterns = [
    path('messages/', views.messages, name='messages'),
    path('deletemessage/<message_id>', views.deletemessage, name='deletemessage'),
    path('writemessage/', views.writemessage, name='writemessage'),
    path('writemessage/<recipient>/', views.writemessage, name='writemessage_r'),
    path('writemessage/<recipient>/<subject>/', views.writemessage, name='writemessage_rs'),
]
 

Profbeats/messager/models.py
from django.db import models

# Create your models here.

class Message(models.Model):
    sender = models.CharField(max_length=20)
    subject = models.CharField(max_length=50, blank=True, default='')
    recipient = models.CharField(max_length=20)
    text = models.TextField(max_length=1000)
    track_id = models.CharField(max_length=22, blank=True, default='')
    created_at = models.DateTimeField(auto_now_add=True)

Profbeats/messager/forms.py
from django import forms
from .models import Message

# Create your forms here.

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['recipient', 'subject', 'text', 'track_id']

Profbeats/messager/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *

import spotipy
from spotipy.oauth2 import SpotifyClientCredentials

from django.contrib import messages as djangomessages

auth_manager = SpotifyClientCredentials(client_id='96652f337059433b8015a2fc3b8922fa', client_secret='bc7324bf495b401abd4018f2a5404054')
sp = spotipy.Spotify(auth='BQBudGJkAEas3zrtctXFBRveiTFae3AIqOC', auth_manager=auth_manager)

def messages(request):
    context = {}

    # You need to be logged in to send/read messages.
    # Redirect to the login page if the user is not logged in.
    if not request.user.is_authenticated:
        djangomessages.warning(request, ("You need to be logged in to read and send messages."))
        return redirect('login')
    
    context['inbox'] = Message.objects.filter(recipient = request.user.get_username()).order_by('-created_at')
    if not context['inbox']:
        djangomessages.info(request, ("Your inbox is empty. Send someone a message to strike up a conversation!"))

    return render(request, 'messager/messages.html', context)

def deletemessage(request, message_id):
    message = Message.objects.get(pk=message_id)
    message.delete()
    djangomessages.success(request, ('Message deleted.'))
    return redirect('messager:messages')

def writemessage(request, recipient=None, subject=None):
    context = {}
    if recipient is not None:
        context['recipient'] = recipient
    if subject is not None:
        context['subject'] = 'RE: ' + subject

    # You need to be logged in to write messages.
    # Redirect to the login page if the user is not logged in.
    if not request.user.is_authenticated:
        djangomessages.warning(request, ("You need to be logged in to read and send messages."))
        return redirect('login')

    if request.method == 'POST':
        form = MessageForm(request.POST)

        if form.is_valid():
            msg = form.save(commit=False)
            msg.sender = request.user.get_username()
            if not msg.subject:
                msg.subject = "(no subject)"
            msg.save()
            djangomessages.success(request, ("Your message was sent."))
            return redirect('messager:messages')

        else:
            print(form.errors.as_data())

    else:
        form = MessageForm()
        context['form'] = form
    return render(request, 'messager/writemessage.html', context)

Profbeats/messager/templates/messager/messages.html
{% extends 'base.html' %}

{% block title %}Messager{% endblock %}

{% block content %}
<br>
    <center>
        <h2>Messages</h2>
    </center>
<br>

{% if messages %}
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
        <div class="alert alert-success alert-dismissable" role="alert">
            <button class="close" data-dismiss="alert">
                X
            </button>
            <center>{{ message }}</center>
        </div>
        {% else %}
        <div class="alert alert-info" role="alert">
            <center>{{ message }}</center>
        </div>
        {% endif %}
    {% endfor %}
{% endif %}

{% if inbox %}
<div class="container">
    {% for msg in inbox %}
    <div class="row border">
        <div class=" col m-2 text-left font-weight-bold">From: {{ msg.sender }}</div>
        <div class="col m-2 text-center font-weight-bold">{{ msg.subject }}</div>
        <div class="col m-2 text-right font-weight-bold"> {{ msg.created_at|date:'D, M j, Y, f A' }}</div>
    </div>
        <div class="row border-left border-top border-right">
            <div class="col m-2">{{ msg.text }}</div>
        </div>
        {% if msg.track_id %}
        <div class="row border-left border-right">
            <div class="col m-2 text-muted">{{ msg.sender }} recommended a song:</div>
        </div>
        <div class="row border-left border-right">
            <div class="col m-2">
                <iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/{{ msg.track_id }}" width="100%" height="80" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
            </div>
        </div>
        {% endif %}
        <div class="row border mb-4">
            <div class="col m-2 text-left"><a class="btn btn-secondary" href="{% url 'messager:writemessage_rs' msg.sender msg.subject %}">Reply</a></div>
            <div class="col m-2 text-right"><a class="btn btn-danger" href="{% url 'messager:deletemessage' msg.id %}">Delete</a></div>
        </div>
    {% endfor %}
</div>
{% endif %}

<center>
    <a class="btn btn-dark btn-lg" href="{% url 'messager:writemessage' %}">Write a message</a>
</center>
<br>
{% endblock %}

Profbeats/messager/templates/messager/writemessage.html
{% extends 'base.html' %}

{% block title %}Messager | Write Message{% endblock %}

{% block content %}
<br>
    <center>
        <h2>Compose a message</h2>
    </center>
<br>
<form method="POST">
    {% csrf_token %}
    <div class="form-row">
        <div class="col">
            <div class="form-group">
            <label for="recipient">To:</label>
            <textarea class="form-control form-control-sm" id="recipient" name="recipient" placeholder="Enter the recipient's username here." rows="1" maxlength="20" required>{% if recipient %}{{ recipient }}{% endif %}</textarea>
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="subject">Subject:</label>
                <textarea class="form-control form-control-sm" id="subject" name="subject" placeholder="Enter the subject of your message here (optional)." rows="1" maxlength="50">{% if subject %}{{ subject }}{% endif %}</textarea>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="text">Message:</label>
        <textarea class="form-control" id="text" name="text" placeholder="Enter your message here (max 1000 characters)." rows="5" maxlength="1000" required></textarea>
    </div>
    <div class="form-group">
        <label for="track_id">Track ID:</label>
        <textarea class="form-control form-control-sm" id="track_id" name="track_id" placeholder="You can recommend a song to the recipient by pasting a 22-character-long track ID here." rows="1" maxlength="22"></textarea>
    </div>
    <center>
        <input class="btn btn-dark btn-lg" type="submit" value="Send message">
    </center>
</form>
<br>
{% endblock %}